# Generated by Django 2.0.5 on 2018-07-27 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'Contain',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('CardNumber', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrinkName', models.CharField(max_length=255)),
                ('DrinkSize', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
            options={
                'db_table': 'Drinks',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=255)),
                ('EmployeePosition', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('IngredientID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('IngredientName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='MadeWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient', models.ForeignKey(db_column='IngredientID', on_delete=django.db.models.deletion.CASCADE, to='ordering.Ingredients')),
            ],
            options={
                'db_table': 'MadeWith',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('MenuItemID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
            ],
            options={
                'db_table': 'MenuItem',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Cost', models.FloatField()),
                ('DeliverySuccess', models.BooleanField(default=False)),
                ('DeliveryInstructions', models.CharField(max_length=255)),
                ('OrderPlacementTime', models.DateTimeField()),
                ('OrderCompletionTime', models.DateTimeField()),
                ('DeliveryOrPickup', models.CharField(choices=[('D', 'Delivery'), ('P', 'Pickup')], max_length=1)),
                ('Customer', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='ordering.Customer')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SandwichName', models.CharField(max_length=255)),
                ('SandwichSize', models.CharField(choices=[('H', '6-inch'), ('F', 'Foot-long')], max_length=1)),
                ('MenuItem', models.ForeignKey(db_column='MenuItemID', on_delete=django.db.models.deletion.CASCADE, to='ordering.MenuItem')),
            ],
            options={
                'db_table': 'Sandwich',
            },
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SnackName', models.CharField(max_length=255)),
                ('MenuItem', models.ForeignKey(db_column='MenuItemID', on_delete=django.db.models.deletion.CASCADE, to='ordering.MenuItem')),
            ],
            options={
                'db_table': 'Snacks',
            },
        ),
        migrations.CreateModel(
            name='WorksAt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='ordering.Employee')),
                ('Restaurant', models.ForeignKey(db_column='RestaurantID', on_delete=django.db.models.deletion.CASCADE, to='ordering.Restaurant')),
            ],
            options={
                'db_table': 'WorksAt',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='Restaurant',
            field=models.ForeignKey(db_column='RestaurantID', on_delete=django.db.models.deletion.CASCADE, to='ordering.Restaurant'),
        ),
        migrations.AddField(
            model_name='madewith',
            name='MenuItem',
            field=models.ForeignKey(db_column='MenuItemID', on_delete=django.db.models.deletion.CASCADE, to='ordering.MenuItem'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='MenuItem',
            field=models.ForeignKey(db_column='MenuItemID', on_delete=django.db.models.deletion.CASCADE, to='ordering.MenuItem'),
        ),
        migrations.AddField(
            model_name='contain',
            name='MenuItem',
            field=models.ForeignKey(db_column='MenuItemID', on_delete=django.db.models.deletion.CASCADE, to='ordering.MenuItem'),
        ),
        migrations.AddField(
            model_name='contain',
            name='Order',
            field=models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='ordering.Orders'),
        ),
        migrations.AlterUniqueTogether(
            name='worksat',
            unique_together={('Restaurant', 'Employee')},
        ),
        migrations.AlterUniqueTogether(
            name='madewith',
            unique_together={('MenuItem', 'Ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='contain',
            unique_together={('Order', 'MenuItem')},
        ),
    ]
